name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./webapp
          push: false
          load: true
          tags: webapp:latest

      - name: Copy files to VM
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y openssh-client

          # Setup SSH key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

          # Copy files to VM
          scp -o StrictHostKeyChecking=no -i id_rsa webapp/index.html adminuser@52.169.72.144:~/webapp/
          scp -o StrictHostKeyChecking=no -i id_rsa webapp/Dockerfile adminuser@52.169.72.144:~/webapp/

          # SSH into VM and update container
          ssh -o StrictHostKeyChecking=no -i id_rsa adminuser@52.169.72.144 "
            cd ~/webapp
            docker build -t webapp:latest .
            docker stop mywebapp || true
            docker rm mywebapp || true
            docker run -d -p 80:80 --name mywebapp webapp:latest
          "
